version: "3.8"

services:
    db:
        build: .
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: ibllog
            POSTGRES_USER: user
            POSTGRES_PASSWORD: secretpassword
        volumes:
            - ./db_data:/var/lib/postgresql/data

volumes:
    db_data:
